# Generated by Django 4.1.4 on 2022-12-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
