# Generated by Django 4.1.4 on 2022-12-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="Plan_name",
        ),
    ]
